"""Initial migrate

Revision ID: d731b4a0c5cb
Revises: 22a1f742b3f8
Create Date: 2026-08-14 07:57:19.818234

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd731b4a0c5cb'
down_revision = '22a1f742b3f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_categories_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('event_categories_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('from_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('to_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('location_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.String(length=36), nullable=False))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=60),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('img_url',
               existing_type=mysql.VARCHAR(length=256),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('events_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key(None, 'locations', ['location_id'], ['id'])
        batch_op.drop_column('organizer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', mysql.VARCHAR(length=36), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('events_ibfk_1'), 'users', ['organizer_id'], ['id'])
        batch_op.alter_column('img_url',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=256),
               existing_nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=60),
               existing_nullable=False)
        batch_op.drop_column('author_id')
        batch_op.drop_column('location_id')
        batch_op.drop_column('views')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('to_time')
        batch_op.drop_column('from_time')
        batch_op.drop_column('date')

    with op.batch_alter_table('event_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_categories_ibfk_2'), 'categories', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('event_categories_ibfk_1'), 'events', ['event_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    # ### end Alembic commands ###
